name: Sideload to iPhone

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Verify project root
        run: |
          ls -la
          pwd
          cat pubspec.yaml || echo "pubspec.yaml not found!"

      - name: Get deps
        run: flutter pub get

      - name: Pod install
        run: cd ios && pod install

      - name: Build & Install
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          UDID: ${{ secrets.UDID }}
        run: |
          security unlock-keychain -p "github" ~/Library/Keychains/login.keychain-db
          flutter build ios --debug
          xcrun devicectl device install app --device-id $UDID build/ios/iphoneos/Runner.app